In [2]:
from __future__ import print_function
import torch

## 创建张量

In [3]:
# 创建一个没有初始化的矩阵
x = torch.empty(5, 3)
print(x)

tensor([[6.3550e-22, 1.5498e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
# 创建一个随机初始化的矩阵
x = torch.rand(5, 3)
print(x)

tensor([[0.8842, 0.7095, 0.3854],
        [0.7909, 0.4154, 0.4836],
        [0.2167, 0.1464, 0.6554],
        [0.8275, 0.1238, 0.2904],
        [0.6208, 0.2103, 0.8110]])


In [6]:
# 创建一个填充0且数据类型为long的矩阵
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
# 直接从数据构造张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
# 根据已有的张量创建张量
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)
x = torch.randn_like(x, dtype=torch.float)    # 重载 dtype!
print(x)                                      # 结果size一致

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1713,  0.6240,  0.2867],
        [ 0.6044,  1.6001, -2.0201],
        [ 0.2541,  1.0586,  2.1091],
        [-0.5638,  0.0644,  1.5197],
        [ 0.3798,  0.0080,  2.2716]])


In [9]:
# 获取张量的形状
print(x.size())

torch.Size([5, 3])


## 运算

In [10]:
# 加法
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.5952,  1.3245,  1.0296],
        [ 0.8488,  1.9436, -1.0340],
        [ 0.5949,  1.5006,  2.3448],
        [-0.4855,  0.9811,  1.5879],
        [ 1.1625,  1.0050,  2.9213]])


In [11]:
# 加法2
print(torch.add(x, y))

tensor([[ 0.5952,  1.3245,  1.0296],
        [ 0.8488,  1.9436, -1.0340],
        [ 0.5949,  1.5006,  2.3448],
        [-0.4855,  0.9811,  1.5879],
        [ 1.1625,  1.0050,  2.9213]])


In [12]:
# 加法：提供一个输出张量作为参数
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.5952,  1.3245,  1.0296],
        [ 0.8488,  1.9436, -1.0340],
        [ 0.5949,  1.5006,  2.3448],
        [-0.4855,  0.9811,  1.5879],
        [ 1.1625,  1.0050,  2.9213]])


In [16]:
# 加法：原位/原地操作（in-place）
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.5952,  1.3245,  1.0296],
        [ 0.8488,  1.9436, -1.0340],
        [ 0.5949,  1.5006,  2.3448],
        [-0.4855,  0.9811,  1.5879],
        [ 1.1625,  1.0050,  2.9213]])


注意：

任何一个in-place改变张量的操作后面都固定一个_。例如x.copy_(y)、x.t_()将更改x

In [17]:
# 改变张量的大小：如果你想改变一个张量的大小或者形状，你可以使用torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
# 如果你有一个元素tensor，使用.item()来获得这个value
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.2072])
0.20720399916172028


## NumPy桥

将一个Torch张量转换为一个NumPy数组是轻而易举的事情，反之亦然。
Torch张量和NumPy数组将共享它们的底层内存位置，因此当一个改变时,另外也会改变。

In [25]:
# 将torch的Tensor转换为numpy数组
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [26]:
# 看numpy数组是如何改变里面的值的
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
# 将numpy数组转换为torch张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有CPU上的张量(CharTensor除外)都支持与Numpy的相互转换。

## CUDA张量

In [28]:
# 当GPU可用时,我们可以运行以下代码
# 我们将使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # 直接在GPU上创建tensor
    x = x.to(device)                       # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([1.2072], device='cuda:0')
tensor([1.2072], dtype=torch.float64)
